[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm']

[phases.install]
cmds = ['npm run railway:install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_VERSION = '20'
NPM_CONFIG_INCLUDE = 'dev'
NIXPACKS_NODE_VERSION = '20'
